### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-vda0a#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by prashantlakra** [comment]
![placeholder](https://user-images.githubusercontent.com/8759236/182232908-e75989f3-add0-49a0-ba86-186b8997f05a.png)

bug fix

**Comment by prashantlakra** [comment]
![placeholderfix](https://user-images.githubusercontent.com/8759236/182233965-12cd5aea-3251-46ba-9ac0-4140dd98d710.png)

**Comment by prashantlakra** [comment]
fixed the bug
